---
- name: Upload files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'k8s.conf', dest: '/etc/sysctl.d/k8s.conf'}
    - { src: '99-kubernetes-cri.conf', dest: '/etc/sysctl.d/99-kubernetes-cri.conf'}

- name: Restart sysctl
  shell: |
    sysctl --system
  tags: skip_ansible_lint

- name: Init kubernetes cluster
  shell: |
    kubeadm init --apiserver-advertise-address={{ advertiseip | default(hostvars[inventory_hostname].ansible_host) }} --pod-network-cidr={{ podnetworkcidr | default('10.244.0.0') }}/16 > /var/log/kubeadm.log
  when: inventory_hostname == groups['master'][0]
  tags: skip_ansible_lint
  delegate_to: "{{ groups['master'][0] }}"
