---
- name: Disable & remove k8s services
  service:
    name: kubelet
    state: stopped
    enabled: no
  ignore_errors: true

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Remove unused dir
  file:
    state: absent
    dest: "{{ item }}"
  with_items:
    - '/etc/kubernetes/'
    - '/usr/lib/systemd/system/kubelet.service.d/'
    - '/usr/lib/systemd/system/kubelet.service'
    - '/etc/systemd/system/kubelet.service.d'
    - '/etc/sysconfig/kubelet'
    - '/etc/sysctl.d/99-kubernetes-cri.conf'
